<?php

namespace App\Http\Controllers\Admin;

use \Backpack\PermissionManager\app\Http\Controllers\UserCrudController as OriginUserCrudController;
use Backpack\CRUD\app\Library\CrudPanel\CrudPanelFacade as CRUD;

class UserCrudController extends OriginUserCrudController
{

    protected function addUserFields()
    {
        parent::addUserFields();
        CRUD::field('address')->type('textarea');
        CRUD::field('phone');
        CRUD::field('bank_name');
        CRUD::field('bank_branch');
        CRUD::field('bank_account_name');
        CRUD::field('bank_account_number');
    }

    public function setupListOperation()
    {
        parent::setupListOperation(); // TODO: Change the autogenerated stub
        CRUD::column('username');
        CRUD::column('code');
    }

    public function setupCreateOperation()
    {
        CRUD::field('username');
        parent::setupCreateOperation(); // TODO: Change the autogenerated stub
    }

}
